- name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: MONGODB_URI,REDIS_ADDR,JWT_SECRET_KEY,ECR_REGISTRY
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker pull $ECR_REGISTRY/starttech-backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d \
            --name backend \
            -p 8080:8080 \
            -e MONGO_URI=$MONGODB_URI \
            -e REDIS_ADDR=$REDIS_ADDR \
            -e JWT_SECRET_KEY=$JWT_SECRET_KEY \
            $ECR_REGISTRY/starttech-backend:latest
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}